# Generated by Django 4.1.1 on 2022-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('tuesday', 'tuesday'), ('monday', 'monday'), ('friday', 'friday'), ('thursday', 'thursday'), ('wednesday', 'wednesday')], max_length=100, verbose_name='Day'),
        ),
    ]
