# Generated by Django 4.1.1 on 2022-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher_room1',
            field=models.CharField(default='teacher', max_length=100, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher_room2',
            field=models.CharField(default='teacher', max_length=100, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher_room3',
            field=models.CharField(default='teacher', max_length=100, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher_room4',
            field=models.CharField(default='teacher', max_length=100, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher_room5',
            field=models.CharField(default='teacher', max_length=100, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher_room6',
            field=models.CharField(default='teacher', max_length=100, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time1',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time16',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time2',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time3',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time4',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time5',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('friday', 'friday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('monday', 'monday'), ('thursday', 'thursday')], max_length=100, verbose_name='Day'),
        ),
    ]
