# Generated by Django 4.1.1 on 2022-10-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_schedule_teacher_room1_schedule_teacher_room2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('thursday', 'thursday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('friday', 'friday'), ('monday', 'monday')], max_length=100, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time1',
            field=models.CharField(max_length=100, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time16',
            field=models.CharField(default='time', max_length=100, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time2',
            field=models.CharField(default='time', max_length=100, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time3',
            field=models.CharField(default='time', max_length=100, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time4',
            field=models.CharField(default='time', max_length=100, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time5',
            field=models.CharField(default='time', max_length=100, verbose_name='Время'),
        ),
    ]
