# Generated by Django 4.1.1 on 2022-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_schedule_day_alter_schedule_time1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='time16',
            new_name='time6',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('friday', 'friday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('tuesday', 'tuesday')], max_length=100, verbose_name='Day'),
        ),
    ]
