# Generated by Django 4.1.1 on 2022-10-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_time16_schedule_time6_alter_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='first',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='second',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sixth',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher_room6',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='third',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time4',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time5',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time6',
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.CharField(default='Friday', max_length=100, verbose_name='Friday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.CharField(default='Group name', max_length=100, verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lesson',
            field=models.IntegerField(default=11, verbose_name='Lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.CharField(default='Monday', max_length=100, verbose_name='Monday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.CharField(default='Thursday', max_length=100, verbose_name='Thursday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.CharField(default='Tuesday', max_length=100, verbose_name='Tuesday'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.CharField(default='Wednesday', max_length=100, verbose_name='Wednesday'),
        ),
    ]
