# Generated by Django 4.1.1 on 2022-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_schedule_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(default='Time', max_length=100, verbose_name='time'),
        ),
    ]
