# Generated by Django 4.1.1 on 2022-10-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_schedule_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
