# Generated by Django 4.1.1 on 2022-10-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='Group name', max_length=100, verbose_name='Group')),
                ('lesson', models.CharField(default='lesson', max_length=10, verbose_name='Lesson')),
                ('monday', models.CharField(default='Monday', max_length=100, verbose_name='Monday')),
                ('teacher_room1', models.CharField(default='teacher', max_length=100, verbose_name='Учитель')),
                ('tuesday', models.CharField(default='Tuesday', max_length=100, verbose_name='Tuesday')),
                ('teacher_room2', models.CharField(default='teacher', max_length=100, verbose_name='Учитель')),
                ('wednesday', models.CharField(default='Wednesday', max_length=100, verbose_name='Wednesday')),
                ('teacher_room3', models.CharField(default='teacher', max_length=100, verbose_name='Учитель')),
                ('thursday', models.CharField(default='Thursday', max_length=100, verbose_name='Thursday')),
                ('teacher_room4', models.CharField(default='teacher', max_length=100, verbose_name='Учитель')),
                ('friday', models.CharField(default='Friday', max_length=100, verbose_name='Friday')),
                ('teacher_room5', models.CharField(default='teacher', max_length=100, verbose_name='Учитель')),
                ('time', models.CharField(default='Time', max_length=100, verbose_name='time')),
            ],
        ),
    ]
