# Generated by Django 4.1.1 on 2022-10-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondcourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule2',
            name='day',
            field=models.CharField(default='Date', max_length=100, verbose_name='date'),
        ),
    ]
